type: "position_controllers/JointGroupPositionController"
joints:
  - l_back_shoulder_to_body
  - l_back_shoulder2_to_shoulder
  - l_back_shoulder2_to_knee
  - l_back_ankle
  # - r_back_final_track_joint
